server:
  port: 8100

spring:
  application:
    name: aimianshi
  # 默认 dev 环境
  profiles:
    active: dev

  datasource:
    driver-class-name: ${mianshiya.datasource.driver-class-name}
    url: jdbc:mysql://${mianshiya.datasource.host}:${mianshiya.datasource.port}/${mianshiya.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mianshiya.datasource.username}
    password: ${mianshiya.datasource.password}
    # Druid datasource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 60000
      # 一个连接最小生存时间 ms
      min-evictable-idle-time-millis: 300000
      # 检测空闲连接时间周期 ms
      time-between-eviction-runs-millis: 60000
      # 配置扩展插件：stat-监控统计，log4j-日志，wall-防火墙（防止SQL注入），去掉后，监控界面的sql无法统计
      filters: stat,wall
      # 检测连接是否有效的 SQL语句，为空时以下三个配置均无效
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效，默认true，开启后会降低性能
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效，默认false，开启后会降低性能
      test-on-return: true
      # 申请连接时如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效，默认false，建议开启，不影响性能
      test-while-idle: true
      # 是否开启 StatViewServlet
      stat-view-servlet:
        enabled: true
        # 访问监控页面 白名单，默认127.0.0.1
        allow: 127.0.0.1
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
      # FilterStat
      filter:
        stat:
          # 是否开启 FilterStat，默认true
          enabled: true
          # 是否开启 慢SQL 记录，默认false
          log-slow-sql: true
          # 慢 SQL 的标准，默认 3000，单位：毫秒
          slow-sql-millis: 5000
          # 合并多个连接池的监控数据，默认false
          merge-sql: false


  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出日志
    map-underscore-to-camel-case: true # 下划线转驼峰
  mapper-locations: classpath:mapper/**/*.xml # mapper.xml
  type-aliases-package: com.xxx.mianshiya.**.domain.entity # 别名扫描包
  global-config:
    db-config:
      update-strategy: not_null # 只有当字段值不为null时才更新该字段
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  secret-key: ${mianshiya.jwt.secret-key}
  ttl: ${mianshiya.jwt.ttl}
  token-name: ${mianshiya.jwt.token-name}
